
-- Retrieve all records from the sales_data table.
select * from sales_data 

-- What was the total revenue generated by the company over the course of the year?
Select Sum(revenue) as Total_Revenue from sales_data

-- Which product had the highest revenue? How much revenue did it generate?
select top 1 product , sum(revenue) As Highest_Revenue from sales_data
group by product order by Highest_Revenue desc

-- What was the average price of a product sold by the company?
select avg(price) as Avg_Price
from sales_data 

-- What was the total quantity of products sold by the company?
Select Sum(quantity) as Total_Quantity from sales_data

-- Which category had the highest revenue? How much revenue did it generate?
select top 1 category , sum(revenue) as Highest_Revenue from sales_data
group by category order by Highest_Revenue desc

-- What was the average revenue per sale?
select avg(revenue) as Avg_Revenue from sales_data

-- What was the total revenue generated in each quarter of the year? (i.e. Q1, Q2, Q3, Q4)
Select datepart(quarter , date) as Quarter, Sum(revenue) as Total_Revenue 
from sales_data 
group by datepart(quarter , date) order by Quarter

-- Find the total revenue for each category.
select category , sum(revenue) as Total_revenue from sales_data
group by category

-- Calculate the total quantity sold for each product.
select product , sum(quantity) as Total_quantity from sales_data
group by product

-- Retrieve sales data for products in the "electronics" category.
select * from sales_data where category = 'electronics'

-- Find the highest price for each product.
select product , max(price) as Highest_Price from sales_data 
group by product

-- Retrieve sales data for sales made in January 2022.
select * from sales_data where month(date) = 1

-- Find the total revenue generated by each product in the "clothing" category.
select product , sum(revenue) As Total_Revenue from sales_data
where category = 'Clothing'
group by product 

-- Calculate the total quantity sold per month
select Month(date) as Months ,
sum(quantity) as Total_Quantity
from sales_data
group by Month(date)

-- Retrieve the details of the sale with the highest revenue.
select * from sales_data 
where revenue = (select max(revenue) from sales_data)

select top 1 * from sales_data 
order by revenue desc

-- Find the average price of products in each category.
select category , avg(price) as Avg_Price from sales_data
group by category

-- Calculate the total revenue generated each day.
select date , Sum(revenue) as Total_Revenue 
from sales_data group by date

-- Retrieve sales data for products with a price greater than $100.
select * from sales_data where price > 100

-- Find the total number of sales made in each category.
select category , count(*) Total_Sales from sales_data
group by category

-- Calculate the average quantity sold per sale
select avg(quantity) as Avg_Quantity
from sales_data;

-- Retrieve sales data for the top 5 products by total revenue.
select top 5 product , sum(revenue) as Total_Revenue from sales_data
group by product order by Total_Revenue desc

-- Retrieve the product with the highest average revenue per sale.
select top 1 product , avg(revenue) Avg_Revenue from sales_data
group by product order by Avg_Revenue desc

-- Find the total number of unique products sold.
select count(distinct product) Total_Products from sales_data

-- Find the total quantity sold for each category per month.
select category , Month(date) as Month , sum(quantity) as Total_quantity
from sales_data
group by category , Month(date)

-- Calculate the total revenue and total quantity sold per product.
select product , sum(revenue) as Total_Revenue , sum(quantity) as Total_Quantity
from sales_data
group by product

-- Retrieve the details of the sales made for products with a quantity greater than 10.
select * from sales_data 
where quantity > 10

-- Calculate the average price per product for each category.
select category , avg(price) as Avg_Price 
from sales_data
group by category

-- Retrieve the top 10 days with the highest total revenue.
select top 10 date , sum(revenue) as Total_Revenue 
from sales_data 
group by date order by Total_Revenue desc

-- Find the category with the highest total quantity sold.
select top 1 category , sum(quantity) as Total_Quantity
from sales_data
group by category 
order by Total_Quantity desc

-- Calculate the total revenue for each product in the "electronics" category per month.
select Month(date) as Month , product , sum(revenue) as Total_Revenue
from sales_data 
where category = 'Electronics' 
group by Month(date) , product 
order by Month , Total_Revenue